name: Test PR - Node Matrix
on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'examples/**'
      - '!examples/monaco-graphql-webpack'
jobs:
  unit:
    name: Unit Tests in node Matrix
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: ['14', '16', '17', '18']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --immutable

      - name: Build
        run: yarn build

      - name: Run Unit Tests
        run: yarn test
