name: Pre-Release

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'examples/**'
      - '!examples/monaco-graphql-webpack'

jobs:
  publish-canary:
    name: Publish Pre-Release
    runs-on: ubuntu-latest
    # only on next/
    # only on non-forked branches. IMPORTANT!!!!
    if:  ${{ startsWith(github.head_ref, 'next/') && !github.event.pull_request.head.repo.fork }}
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'current'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --immutable

      - name: Setup NPM credentials
        run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release Canary
        id: canary
        uses: 'kamilkisiela/release-canary@master'
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          npm-script: 'yarn release:canary'
          changesets: true
      - name: Publish a message
        if: steps.canary.outputs.released == 'true'
        uses: 'dotansimha/pr-comment@master'
        with:
          commentKey: canary
          message: |
            The latest changes of this PR are available as canary in npm (based on the declared `changesets`):

            ```
            ${{ steps.canary.outputs.changesetsPublishedPackages}}
            ```
          bot-token: ${{ secrets.GITHUB_TOKEN }}
          bot: 'github-actions[bot]'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish a empty message
        if: steps.canary.outputs.released == 'false'
        uses: 'dotansimha/pr-comment@master'
        with:
          commentKey: canary
          message: |
            The latest changes of this PR are not available as canary, since there are no linked `changesets` for this PR.
          bot-token: ${{ secrets.GITHUB_TOKEN }}
          bot: 'github-actions[bot]'
          github-token: ${{ secrets.GITHUB_TOKEN }}
